# track selection
alang=ja,jp,jpn,japanese,en,eng,english,English,enUS,en-US
sid=no

# watch later
save-position-on-quit=yes

# subtitles
sub-auto=no
sub-visibility=no

# osd
osc=no

# screenshot
screenshot-template="%F_%wHh%wMm%wSs%wTms"
screenshot-dir=~/Pictures/Screenshots
