local keymap = vim.keymap.set

keymap("i", "kj", "<Esc>", { desc = "exit insert mode with kj" })
keymap("n", "<C-Left>", "<Cmd>vertical resize -1<CR>", { desc = "decrease current window width" })
keymap("n", "<C-Right>", "<Cmd>vertical resize +1<CR>", { desc = "increase current window width" })
keymap("n", "<C-S-Down>", "<Cmd>resize -1<CR>", { desc = "decrease current window height" })
keymap("n", "<C-S-Up>", "<Cmd>resize +1<CR>", { desc = "increase current window height" })
keymap("n", "<C-d>", "<C-d>zz", { desc = "scroll down and center the cursor line" })
keymap("n", "<C-u>", "<C-u>zz", { desc = "scroll up and center the cursor line" })
keymap("n", "<leader>+", "<C-a>", { desc = "increment number" })
keymap("n", "<leader>-", "<C-x>", { desc = "decrement number" })
keymap("n", "<leader>fe", "<Cmd>Explore<CR>", { desc = "open the file explorer" })
keymap("n", "<leader>sc", "<Cmd>close<CR>", { desc = "close current split" })
keymap("n", "<leader>se", "<C-w>=", { desc = "make splits equal size" })
keymap("n", "<leader>sh", "<C-w>s", { desc = "split window horizontally" })
keymap("n", "<leader>sv", "<C-w>v", { desc = "split window vertically" })
keymap("n", "J", "mzJ`z", { desc = "join lines and keep the cursor in the same place" })
keymap("n", "N", "Nzzzv", { desc = "move to the previous search result and center the cursor" })
keymap("n", "n", "nzzzv", { desc = "move to the next search result and center the cursor" })
keymap("v", "<", "<gv", { desc = "indent out the selected lines" })
keymap("v", "<leader>+", "g<C-a>", { desc = "increment number" })
keymap("v", "<leader>-", "g<C-x>", { desc = "decrement number" })
keymap("v", ">", ">gv", { desc = "indent in the selected lines" })
keymap("v", "J", ":m '>+1<CR>gv=gv", { desc = "move down the selected lines" })
keymap("v", "K", ":m '<-2<CR>gv=gv", { desc = "move up the selected lines" })
keymap("v", "p", '"_dp', { desc = "paste over currently selected text without yanking it" })
