local g = vim.g
local opt = vim.opt

g.mapleader = " "
g.maplocalleader = " "
g.netrw_banner = 0
g.netrw_bufsettings = "noma nomod nonu nobl nowrap ro rnu"
g.netrw_hide = 0
g.netrw_liststyle = 3
g.netrw_sizestyle = "H"
opt.autoindent = true
opt.background = "dark"
opt.clipboard = "unnamedplus"
opt.cmdheight = 1
opt.cursorline = true
opt.expandtab = true
opt.hlsearch = false
opt.ignorecase = true
opt.incsearch = true
opt.list = true
opt.listchars = { eol = "↵" }
opt.mouse = ""
opt.scrolloff = 10
opt.shiftwidth = 2
opt.showmode = false
opt.sidescrolloff = 20
opt.signcolumn = "yes"
opt.smartcase = true
opt.softtabstop = 2
opt.splitbelow = true
opt.splitright = true
opt.swapfile = false
opt.tabstop = 2
opt.termguicolors = true
opt.undofile = true
opt.updatetime = 1000
opt.wrap = false
